services:
  db:
    image: mariadb:11.4
    restart: unless-stopped
    env_file: 
      - .env.production
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    build: .
    command: sh -c "pnpm install && pnpm start"
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env.production
    ports:
      - "6000:3000"
    volumes:
      - .:/git-task
      - /git-task/node_modules

volumes:
  dbdata:
