services:
  db:
    image: mariadb:11.4
    container_name: db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: Tw080401!!**
      MYSQL_DATABASE: gittask
      MYSQL_USER: gittask
      MYSQL_PASSWORD: Tw080401!!**

    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-pTw080401!!**"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: cher1shrxd/git-task
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: gittask
      DB_PASSWORD: Tw080401!!**
      DB_NAME: gittask

    ports:
      - "6000:3000"
    restart: unless-stopped

volumes:
  dbdata: