services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: cher1shrxd/git-task-web:latest
    container_name: git-task-app
    restart: unless-stopped

    env_file:
      - .env.production
    ports:
      - "3000:3000"

    depends_on:
      db:
        condition: service_healthy

    networks: [git-task-net]

  db:
    image: mariadb:11
    platforms:
        - linux/amd64
        - linux/arm64
    container_name: git-task-db
    restart: unless-stopped

    env_file:
      - .env.production

    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MARIADB_USER --password=$$MARIADB_PASSWORD --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks: [git-task-net]

volumes:
  db_data:

networks:
  git-task-net:
