import type { Metadata } from "next";
import "./globals.css";
import './tailwind.css';
import {ReactNode} from "react";
import localFont from "next/font/local";
import {CookiesProvider} from "next-client-cookies/server";
import ProgressProvider from "@/components/providers/ProgressProvider";
import QueryProvider from "@/components/providers/QueryProvider";
import Header from "@/components/common/Header";
import Sidebar from "@/components/common/Sidebar";
import AuthSessionProvider from "@/components/providers/SessionProvider";

export const metadata: Metadata = {
  title: "Git-TASK",
  description: "Generated by cher1sh-next-app",
};

const pretendard = localFont({
  src: "../assets/fonts/pretendard.woff2",
  variable: "--font-prendard",
  weight: "100 900",
});


const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className={pretendard.variable}>
        <ProgressProvider>
          <QueryProvider>
            <AuthSessionProvider>
              <CookiesProvider>
                <div className="w-full h-screen bg-bg">
                  <Header />
                  <div className="w-full h-[calc(100%-100px)] flex items-start justify-center">
                    <Sidebar />
                    <div className="w-[calc(100%-400px)] h-full bg-white rounded-tl-4xl shadow-2xl border-l border-t border-gray-300">
                      {children}
                    </div>
                  </div>
                </div>
              </CookiesProvider>
            </AuthSessionProvider>
          </QueryProvider>
        </ProgressProvider>
      </body>
    </html>
  );
}

export default RootLayout;