import type { Metadata } from "next";
import "./globals.css";
import './tailwind.css';
import {ReactNode} from "react";
import localFont from "next/font/local";
import QueryProvider from "@/components/provider/QueryProvider";
import Header from "@/components/common/Header";
import Sidebar from "@/components/common/Sidebar";
import AuthSessionProvider from "@/components/provider/SessionProvider";
import ToastContainer from "@/components/provider/ToastProvider";

export const metadata: Metadata = {
  title: "Git-TASK",
  description: "Generated by cher1sh-next-app",
};

const pretendard = localFont({
  src: "../assets/fonts/pretendard.woff2",
  variable: "--font-prendard",
  weight: "100 900",
});


const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="ko">
      <body className={pretendard.variable}>
        <ToastContainer />
        <QueryProvider>
          <AuthSessionProvider>
            <div className="w-full min-w-300 h-screen bg-gradient-to-r from-blue-200 to-purple-400 flex">
              <Sidebar />
              <div className="w-[calc(100%-320px)] 2xl:w-[calc(100%-400px)] h-full flex flex-col items-start justify-center">
                <Header />
                <div className="w-full h-[calc(100%-72px)] 2xl:h-[calc(100%-100px)] bg-white rounded-tl-4xl shadow-2xl overflow-scroll pb-10">
                  {children}
                </div>
              </div>
            </div>
          </AuthSessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}

export default RootLayout;